apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - image: 'lloesche/valheim-server:latest'
          name: 'valheim-server'
          env:
            - name: SERVER_NAME
              value: {{ .Values.serverName }}
            - name: WORLD_NAME
              value: {{ .Values.worldName }}
            - name: SERVER_PASS
              value: {{ .Values.password }}
            - name: SERVER_PUBLIC
              value: "false"
            - name: TZ
              value: Europe/Berlin
            - name: ADMINLIST_IDS
              value: "{{ .Values.adminListIds }}"
            - name: PERMITTEDLIST_IDS
              value: "{{ .Values.permittedListIds }}"

          ports:
            - containerPort: 2456
              name: game
          volumeMounts:
            - mountPath: /config
              name: valheim-config
            - mountPath: /opt/valheim
              name: valheim-data
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
      volumes:
        - name: valheim-config
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config
        - name: valheim-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data


